### PR TITLE
feat: add getter and setter for halaa ownership

### PR DESCRIPTION
**Pull request by 55Honey**
Co-authored by @r-o-b-o-t-o 

Adds new Global methods:
SetOwnerHalaa($teamId) //0=Alliance, 1 = Horde
GetOwnerHalaa() // returns { 0 or 1 for owner, $slider }

Tested with:
```lua
local function command( event, player, command, chathandler )
    if command == 'yx' then
        chathandler:SendSysMessage('SetOwnerHalaa(0)')
        SetOwnerHalaa(0)
    elseif command == 'as' then
            chathandler:SendSysMessage('SetOwnerHalaa(1)')
            SetOwnerHalaa(1)
    elseif command == 'qw' then
            chathandler:SendSysMessage('SetOwnerHalaa(2)')
            SetOwnerHalaa(2)
    elseif command == 'asdf' then
        local owner
        local slider
        owner, slider = GetOwnerHalaa()
        chathandler:SendSysMessage('GetOwnerHalaa(): '..owner..' slider: '..slider)
    end
    return false
end

RegisterPlayerEvent(42, command)
```

### CODE REVIEW

**Comment by r-o-b-o-t-o** [comment]
Your commit is missing the methods in `LuaFunctions.cpp`

**Comment by 55Honey** [comment]
Happens when you dev on one machine and push/pull on the other. 🤐  Thanks for the reminder!

**Review by r-o-b-o-t-o — APPROVED** [review]

**Comment by heyitsbench** [comment]
Seems this has caused build errors:
```
In file included from /home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:20:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/GlobalMethods.h:3349:65: fatal error: too few arguments to function call, single argument 'spawnId' was not specified
        OPvPCapturePointNA* halaa = nagrandPvp->GetCapturePoint();
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/OutdoorPvP/OutdoorPvP.h:276:5: note: 'GetCapturePoint' declared here
    OPvPCapturePoint* GetCapturePoint(ObjectGuid::LowType spawnId) const
    ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:762: modules/CMakeFiles/modules.dir/mod-eluna/src/LuaEngine/LuaFunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1235: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by 55Honey** [comment]
Thanks for the heads-up @heyitsbench 
https://github.com/azerothcore/azerothcore-wotlk/pull/14394 still needs to be merged. Then it's gonna be fixed.
I had my fingers too quick there with the merge button.

**Pull request merged**
