### PR TITLE
Fix unused variable warning in GlobalMethods:Ban()

### PR DESCRIPTION
**Pull request by sudlud**

### CODE REVIEW

**Comment by 55Honey** [comment]
Let's get rid of what's not required for AC all together.

There was a reorganisation of the Eluna master repo. Each core now has its own set of files without the need of ifdefs in each file. That's to be ported, but we can start anywhere.

**Comment by sudlud** [comment]
@55Honey i'm reworking this to drop all non-AC-relevant code so we will get rid of most #if #else #endif blocks

should I go as far as assuming we are at AZEROTHCORE with WOTLK beeing set and remove any code related to e.g. CLASSIC/TBC/MISTS/MANGOS/TRINITY/...?

there's a lot of switches depending on the expansion define, but for AC this would always be set to WOTLK?

or would this go too far?

**Comment by 55Honey** [comment]
In short: yes.

There was a closed PR lately, which wasn't merged because it was closed before we had a chance to review it, which claimed to remove all the `ifdef`s. I am not sure if you can dig it up so we can diff-merge.

**Comment by sudlud** [comment]
alright then i might need to revisit this within the next days, for now it removes almost all #if blocks

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
